### ISSUE TITLE
Are multi stage images supported?

### ISSUE THREAD

**Issue by ad-si** [hadolint/language-docker#21]
e.g.

```dockerfile
FROM node AS builder
…
```

**Comment by lorenzo** [comment]
Yes, multistage images are the reason this project exists at all.

That said, it works much better when using multistage builds with ONBUILD instructions. That means, having each stage in a different file.

Do you need guidance in using this tool?

**Comment by ad-si** [comment]
If I recall correctly, this is not the same!

With builder images you can copy just a few things from one image to the next:

```dockerfile
COPY --from=builder /var/app/node_modules node_modules
```

This is not possible with onbuild images.

**Comment by ad-si** [comment]
This is the documentation for it: 
https://docs.docker.com/develop/develop-images/multistage-build/

**Comment by ad-si** [comment]
I guess I should have read it until the end 😅:

> When using multi-stage builds, you are not limited to copying from stages you created earlier in your Dockerfile.

I'll try out if I can make it work this way…

**Comment by lorenzo** [comment]
@ad-si Let me know if you need help!

**Comment by ad-si** [comment]
Thanks! Actually, I already have a question. How can I build this:

```dockerfile
COPY --from=builder /var/app/node_modules node_modules
```

**Comment by lorenzo** [comment]
@ad-si are you suing the DSL or using the quasi quoter?

Using the quasi quoter:

```haskell
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE QuasiQuotes       #-}
import Language.Docker
main = putStr $ toDockerfileStr $ do
    [edockerfile|
    FROM node as builder
    FROM node
    COPY --from=builder /var/app/node_modules node_modules
    CMD node something.js
    |]
```

Using the DSL:

```haskell
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE QuasiQuotes       #-}
import Language.Docker
import Language.Docker.Syntax as Syntax

main = putStr $ toDockerfileStr $ do
     from $ "node"  `aliased` "builder"
     copyFrom "builder" ["/var/app/node_modules"] "node_modules"
   where 
    copyFrom img sources dest = copyArgs sources dest Syntax.NoChown (Syntax.CopySource img)
```

I realise now that there should be a helper function in the DSL for this common case. I'll work on that soon. Let me know if this worked for you

**Comment by ad-si** [comment]
Thanks for the examples!

I don't use QuasiQuotes (when possible). Neither a fan of the Docker syntax, nor of Template Haskell.
Would be really could if you'd add first class support to the EDSL. 😁
We use this features basically in every Dockerfile nowadays.

**Comment by lorenzo** [comment]
I'll give a stabat it this weekend... or maybe you want to help me with that? I can guide you if you are interested

**Comment by ad-si** [comment]
Uhm, my real GitHub account (@adius) is currently blocked. I don't want to use this account for contributions. When (if) it gets unlocked I could help out ...

**Comment by ad-si** [comment]
Stupid question: There must be an easier way, right? 😅

```
copy (NonEmpty.fromList [SourcePath "test.json"]) (TargetPath "test.json")
```

**Comment by lorenzo** [comment]
@ad-si both `SourcePath` and `TargetPath` have as `IsString` instance. So if you add these two extensions:

```haskell
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE OverloadedLists #-}
``

You should be able to write:

```haskell
copy ["test.json"] "test.json"
```

**Comment by ad-si** [comment]
Ahhh, the `OverloadedLists` was the crucial part. Must have missed it in your examples…
Thanks a lot!

**Comment by lorenzo** [comment]
@ad-si I'm thinking of changing the DSL for `copy`. what do you think of this?

```haskell
copy $ fromImage "builder" $ ["test.json"] `to` "/app/" 
```

**Comment by ad-si** [comment]
Mh, looks a little to involved for me. Sometime simpler is better. What's wrong with:

```haskell
copyFromStage "builder" ["test.json"] "/app/"
```

**Comment by lorenzo** [comment]
I can for sure offer a simpler version once I get the completed cases sorted out. The complex case is having both from and chows as flags for copy.

The api I suggested a iced would support having both, either or none of the flags (and future flags) in the same syntax.

**Comment by ad-si** [comment]
Ah I see, sounds good.
But the `to` wouldn't be necessary, right?

**Comment by lorenzo** [comment]
Yeah, it is somewhat necessary. I'll explore alternative designs that may also work
