### ISSUE TITLE
How to generate exec form (instead of shell form)?

### ISSUE THREAD

**Issue by ad-si** [hadolint/language-docker#22]
https://docs.docker.com/engine/reference/builder/#entrypoint

`ENTRYPOINT ["yarn", "start", "--"]` vs `ENTRYPOINT yarn start --`

How can I generate the exec form?

**Comment by ad-si** [comment]
Well, `entrypoint "[\"yarn\", \"start\", \"--\"]"` seems to work. But it's awful 😅

**Comment by ad-si** [comment]
`entrypoint $ show ["yarn", "start", "--"]` works too, but it's an awful hack 😂

**Comment by lorenzo** [comment]
@ad-si I agree. That function was not very well thought out when originally created. Your second hack is the cleanest one with now. I'll change that up too along with the changes for `copy`

**Comment by ad-si** [comment]
For future reference: With language extensions it must be like this:

```haskell
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE OverloadedLists #-}

entrypoint $ show (["yarn", "start", "--"] :: [String])
```
