### ISSUE TITLE
Cannot parse image name with "registry:port"

### ISSUE THREAD

**Issue by zemanlx** [hadolint/language-docker#23]
Raised in https://github.com/hadolint/hadolint/issues/169

We cannot parse 

```Dockerfile
FROM myregistry.com:5000/imagename:tag
```

because we expect only one colon `:`, but having a port number in registry name is usual for local/private registries.

---
### Extended description
An image name is made up of slash-separated name components, optionally prefixed by a registry hostname. The hostname must comply with standard DNS rules, but may not contain underscores. If a hostname is present, it may optionally be followed by a port number in the format `:8080`. If not present, the command uses Docker’s public registry located at `registry-1.docker.io` by default. Name components may contain lowercase letters, digits and separators. A separator is defined as a period, one or two underscores, or one or more dashes. A name component may not start or end with a separator.

A tag name must be valid ASCII and may contain lowercase and uppercase letters, digits, underscores, periods and dashes. A tag name may not start with a period or a dash and may contain a maximum of 128 characters.

>https://docs.docker.com/engine/reference/commandline/tag/#extended-description

**Comment by zemanlx** [comment]
Would it be useful to have registry hostname in `Syntax.hs` :confused: @lorenzo?

**Comment by lorenzo** [comment]
heh, I never thought of that case... Dockerfile a a funny mess. I think it may be worth trying to parse as a url first, and then as a normal `image:tag` string. Exposing that it is a url in syntax would also be desirable, I think.

**Comment by zemanlx** [comment]
Thanks for the fix! Can you make a fix release `2.0.2`, please?
