### ISSUE TITLE
Parse RUN agruments do not respect control operators

### ISSUE THREAD

**Issue by zemanlx** [hadolint/language-docker#32]
## Intro
`bash` manpage:
```
       control operator
              A token that performs a control function.  It is one of the following symbols:
              || & && ; ;; ( ) | |& <newline>
```

Control operators are important for decisions which are happening later in `hadolint` https://github.com/hadolint/hadolint/blob/master/src/Hadolint/Rules.hs#L173

This issue has been found through https://github.com/hadolint/hadolint/issues/196

## Current state
```dockerfile
RUN set -ex; apk add --no-cache curl=7.59.0-r0
```

is parsed
```
$ stack repl
> parseString "RUN set -ex; apk add --no-cache ca-certificates=20171114-r0"
Right [InstructionPos {instruction = Run (Arguments ["set","-ex;","apk","add","--no-cache","ca-certificates=20171114-r0"]), sourcename = "<string>", lineNumber = 1}]
```
where `;` is parsed as part of `-ex`.

I believe it is done here
https://github.com/hadolint/language-docker/blob/20c45d269514e45d90cb2eb06c0deb20cdcd6454/src/Language/Docker/Parser.hs#L352

## Desired state

Split `RUN` arguments using white space and selected control operators.

```
$ stack repl
> parseString "RUN set -ex; apk add --no-cache ca-certificates=20171114-r0"
Right [InstructionPos {instruction = Run (Arguments ["set","-ex",";","apk","add","--no-cache","ca-certificates=20171114-r0"]), sourcename = "<string>", lineNumber = 1}]
```

**Comment by lorenzo** [comment]
I really don't think we should concern the parser with this. I'm going to make a change so that the representation is either just a string or a list of arguments, as passed by the user. Then we can use the shellcheck parser to get the actual individual arguments as an AST.

The way it was done here makes little sense as you just discovered.
