### ISSUE TITLE
'label' has to quote arguments

### ISSUE THREAD

**Issue by peti** [hadolint/language-docker#39]
~~~
λ> putDockerfileStr $ label [("maintainer","Peter Simons <simons@cryp.to>")]
LABEL maintainer=Peter Simons <simons@cryp.to>
~~~

gives a Dockerfile that's syntactically incorrect. I would expect `label` to quote that value as needed. Is that not how it's supposed to be used? Do I need to quote these values myself?

**Comment by lorenzo** [comment]
You are using the api correctly, I just forgot to add the quotes in the pretty printer. Thanks for reporting!
