### ISSUE TITLE
Inaccurate version bounds

### ISSUE THREAD

**Issue by hvr** [hadolint/language-docker#45]
As can be seen at

- https://matrix.hackage.haskell.org/package/language-docker@1550016454 

there were a few issues due to inaccurate and/or missing version bounds which affect reverse dependencies of `language-docker`. I've already manually fixed up those up for you via [Hackage metadata revision](https://github.com/haskell-infra/hackage-trustees/blob/master/revisions-information.md), see e.g.

- https://hackage.haskell.org/package/language-docker-8.0.0/revisions/

and you can review the resulting report at 

- https://matrix.hackage.haskell.org/package/language-docker@1550184710

Going forward, we need your help! Please help us ensure a good user experience for users of Hackage/Cabal by the use of the [PVP](http://pvp.haskell.org/faq) mandated lower&upper bounds in order to reduce the penalty on the Hackage infrastructure as well as to avoid unnecessary extra work for you as well as for us Hackage Trustees!

**Comment by lorenzo** [comment]
What is the best way to keep the lower bound up to date?

**Comment by hvr** [comment]
I'm afraid, I don't have a really good answer to testing lower bounds for arbitrary packages. However, for the specific problem of testing lower bounds of non-upgradable packages such as `base`, the best way is currently to simply include all GHCs in your CI test-matrix. 

That's why I created https://github.com/haskell-CI/haskell-ci and the associated Ubuntu PPA for convenient testing with all GHCs back through GHC 7.0 in test-matrices.

If you have any more questions about it, I'm happy to answer them if I can.
