### ISSUE TITLE
Support for heredocs

### ISSUE THREAD

**Issue by potiuk** [hadolint/language-docker#83]
The dockerfile syntax 1.4 introduced a few new things notably #81 and heredocs: https://www.docker.com/blog/introduction-to-heredocs-in-dockerfiles/ but also few more things.

We are already swtiching to use both in our Dockerfiles in apache airflow and we had to disable hadolint for that. It would be great to get support for it :)

**Comment by lorenzo** [comment]
We already support heredocs, you can check the tests https://github.com/hadolint/language-docker/blob/master/test/Language/Docker/ParseRunSpec.hs#L452

**Comment by potiuk** [comment]
Ah cool. I guess release with that is coming :)? If so - it can be closed then (Just to make sure I am using COPY << heredocs - I have not seen an explicit test for that but I saw some example down the file, so I guess it is also supported).

BTW. I am also happy to help with building and releasing the multiplatform image (if we can use the experiment I saw @lorenzo) - even if they are not tested in CI yet, I can test it for Aiflow (and we have hell-of-two-dockerfiles-that-use-nearly-all-possible-dockerfile-features) so that at least the hadoling released image can be multiplatform.

**Comment by potiuk** [comment]
> I think HEREDOCS were only added to `RUN`
> 
> If you can provide somehow the infrastructure to build the images, I would be very happy!

They are also added to COPY - see my new beautiful image here: -> https://github.com/apache/airflow/blob/6821bf2074c03ab791dccfbcb899730761fc5e81/Dockerfile 

Now you will probably understand why we need hadolint to work badly :)) 

This is from this PR: https://github.com/apache/airflow/pull/22492 

Re: Image. I cannot provide the CI infra, unfortunately (this is something we only can use in Airflow). But certainly I am happy to test and prepare scripts to build & push hadolint manually, so that when you release it you will be able to manually push a muti-platform image (this is what we actually do in Airflow when we release, we manually "push" the images from "release manager" machine, because we shoudl do it on "machine in control of release manager" according to Apache Software Foundation rules.

**Comment by lorenzo** [comment]
@potiuk I managed to produce an arm binary in Github actions. I will need a bit more time to re-do the release workflow and cut a new release with the new binaries

**Comment by potiuk** [comment]
Woooho!
