### ISSUE TITLE
Wrong escaping of `\` when parsing ENV instructions

### ISSUE THREAD

**Issue by Lergin** [hadolint/language-docker#86]
When parsing a Dockerfile with an `ENV` instruction containing a `\` in the value of an environment variable, this is not escaped correctly:

```Dockerfile
ENV DOCKER_PASSWORD="aaa\aaa"
```

is parsed to

```
[InstructionPos {instruction = Env [("DOCKER_PASSWORD","aaa\\aaa")], sourcename = "./test.dockerfile", lineNumber = 1}]
```

This shows two `\\` in the parsed value while I would expect there to be none as the `\` is here used to (uselessly) escape the `a`.

**Comment by lorenzo** [comment]
What you see here is the haskell string encoding of the internal structures. In Haskell strings the `\` character needs to be escaped, and that's why you see `\\`.

I you print the AST back to a dockerfile, you should only see one `\`
